/**
 * Shifter API
 * Shifter API
 *
 * The version of the OpenAPI document: latest
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class AccountLogAuthEventsEventRisk {
  'riskDecision'?: string;
  'riskLevel'?: string;
  'compromisedCredentialsDetected'?: boolean;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'riskDecision',
      baseName: 'RiskDecision',
      type: 'string',
    },
    {
      name: 'riskLevel',
      baseName: 'RiskLevel',
      type: 'string',
    },
    {
      name: 'compromisedCredentialsDetected',
      baseName: 'CompromisedCredentialsDetected',
      type: 'boolean',
    },
  ];

  static getAttributeTypeMap() {
    return AccountLogAuthEventsEventRisk.attributeTypeMap;
  }
}
