/**
 * Shifter API
 * Shifter API
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class AccountLogAuthEventsEventFeedback {
    'feedbackValue'?: string;
    'provider'?: string;
    'feedbackDate'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "feedbackValue",
            "baseName": "FeedbackValue",
            "type": "string"
        },
        {
            "name": "provider",
            "baseName": "Provider",
            "type": "string"
        },
        {
            "name": "feedbackDate",
            "baseName": "FeedbackDate",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return AccountLogAuthEventsEventFeedback.attributeTypeMap;
    }
}

