/**
 * Shifter API
 * Shifter API
 *
 * The version of the OpenAPI document: latest
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class CouponGetResponseCoupon {
  'id'?: string;
  'object'?: string;
  'amountOff'?: string;
  'created'?: string;
  'currency'?: string;
  'duration'?: string;
  'durationInMonth'?: string;
  'livemode'?: boolean;
  'maxRedemptions'?: string;
  'metadata'?: { [key: string]: object };
  'name'?: string;
  'percentOff'?: string;
  'redeemBy'?: string;
  'timesRedeemed'?: number;
  'valid'?: boolean;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'id',
      baseName: 'id',
      type: 'string',
    },
    {
      name: 'object',
      baseName: 'object',
      type: 'string',
    },
    {
      name: 'amountOff',
      baseName: 'amount_off',
      type: 'string',
    },
    {
      name: 'created',
      baseName: 'created',
      type: 'string',
    },
    {
      name: 'currency',
      baseName: 'currency',
      type: 'string',
    },
    {
      name: 'duration',
      baseName: 'duration',
      type: 'string',
    },
    {
      name: 'durationInMonth',
      baseName: 'duration_in_month',
      type: 'string',
    },
    {
      name: 'livemode',
      baseName: 'livemode',
      type: 'boolean',
    },
    {
      name: 'maxRedemptions',
      baseName: 'max_redemptions',
      type: 'string',
    },
    {
      name: 'metadata',
      baseName: 'metadata',
      type: '{ [key: string]: object; }',
    },
    {
      name: 'name',
      baseName: 'name',
      type: 'string',
    },
    {
      name: 'percentOff',
      baseName: 'percent_off',
      type: 'string',
    },
    {
      name: 'redeemBy',
      baseName: 'redeem_by',
      type: 'string',
    },
    {
      name: 'timesRedeemed',
      baseName: 'times_redeemed',
      type: 'number',
    },
    {
      name: 'valid',
      baseName: 'valid',
      type: 'boolean',
    },
  ];

  static getAttributeTypeMap() {
    return CouponGetResponseCoupon.attributeTypeMap;
  }
}
