/**
 * Shifter API
 * Shifter API
 *
 * The version of the OpenAPI document: latest
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CouponGetResponseCoupon } from './couponGetResponseCoupon';

export class CouponGetResponse {
  'statusCode'?: number;
  'coupon'?: CouponGetResponseCoupon;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'statusCode',
      baseName: 'statusCode',
      type: 'number',
    },
    {
      name: 'coupon',
      baseName: 'coupon',
      type: 'CouponGetResponseCoupon',
    },
  ];

  static getAttributeTypeMap() {
    return CouponGetResponse.attributeTypeMap;
  }
}
