/**
 * Shifter API
 * Shifter API
 *
 * The version of the OpenAPI document: latest
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class InlineObject2 {
  /**
   * Name of the site
   */
  'siteName'?: string;
  /**
   * All in one WP migration configuration. [true]- Enable making backup file(.wpress)
   */
  'enableAi1wmBackup'?: boolean;
  /**
   * Shifter media CDN configuration. [true]- Enable Media CDN.
   */
  'enableMediaCdn'?: boolean;
  /**
   * Automatic publishing configuration. [true]- Enable automatic publish. Latest artifact will be published automatically when the creating artifact was finished.
   */
  'automation'?: boolean;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'siteName',
      baseName: 'site_name',
      type: 'string',
    },
    {
      name: 'enableAi1wmBackup',
      baseName: 'enable_ai1wm_backup',
      type: 'boolean',
    },
    {
      name: 'enableMediaCdn',
      baseName: 'enable_media_cdn',
      type: 'boolean',
    },
    {
      name: 'automation',
      baseName: 'automation',
      type: 'boolean',
    },
  ];

  static getAttributeTypeMap() {
    return InlineObject2.attributeTypeMap;
  }
}
