/**
 * Shifter API
 * Shifter API
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class InlineResponse2013 {
    /**
    * Job Id which publish the artifact on specific date. This parameter only returns when the date of publish was specified.
    */
    'jobId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "jobId",
            "baseName": "job_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return InlineResponse2013.attributeTypeMap;
    }
}

