/**
 * Shifter API
 * Shifter API
 *
 * The version of the OpenAPI document: latest
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class InlineObject13 {
  'planId'?: InlineObject13.PlanIdEnum;
  'currentPanId'?: InlineObject13.CurrentPanIdEnum;
  'siteId'?: string;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'planId',
      baseName: 'plan_id',
      type: 'InlineObject13.PlanIdEnum',
    },
    {
      name: 'currentPanId',
      baseName: 'current_pan_id',
      type: 'InlineObject13.CurrentPanIdEnum',
    },
    {
      name: 'siteId',
      baseName: 'site_id',
      type: 'string',
    },
  ];

  static getAttributeTypeMap() {
    return InlineObject13.attributeTypeMap;
  }
}

export namespace InlineObject13 {
  export enum PlanIdEnum {
    _01Year = <any>'tier_01_year',
    _01Month = <any>'tier_01_month',
    _02Year = <any>'tier_02_year',
    _02Month = <any>'tier_02_month',
    _03Year = <any>'tier_03_year',
    _03Month = <any>'tier_03_month',
  }
  export enum CurrentPanIdEnum {
    _01Year = <any>'tier_01_year',
    _01Month = <any>'tier_01_month',
    _02Year = <any>'tier_02_year',
    _02Month = <any>'tier_02_month',
    _03Year = <any>'tier_03_year',
    _03Month = <any>'tier_03_month',
  }
}
