/**
 * Shifter API
 * Shifter API
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class InlineObject19 {
    'hookEvent'?: string;
    'url'?: string;
    'method'?: string;
    'enabled'?: string;
    'headers'?: object;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "hookEvent",
            "baseName": "hook_event",
            "type": "string"
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string"
        },
        {
            "name": "method",
            "baseName": "method",
            "type": "string"
        },
        {
            "name": "enabled",
            "baseName": "enabled",
            "type": "string"
        },
        {
            "name": "headers",
            "baseName": "headers",
            "type": "object"
        }    ];

    static getAttributeTypeMap() {
        return InlineObject19.attributeTypeMap;
    }
}

