/**
 * Shifter API
 * Shifter API
 *
 * The version of the OpenAPI document: latest
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class InlineObject1 {
  /**
   * Name of your site name
   */
  'siteName'?: string;
  /**
   * Name of your site name(Legacy Parameter)
   */
  'projectName'?: string;
  /**
   * Team Identifier which the site will be associated. when t
   */
  'team'?: string;
  /**
   * Subscription ID which the site will be associated
   */
  'subscriptionId'?: string;
  /**
   * Plan ID which the site will be associated
   */
  'planId'?: InlineObject1.PlanIdEnum;
  /**
   * Set the directory name if you want to set another directory as root in the site
   */
  'siteSubdir'?: string;
  /**
   * Set to true if you want to use Shifter manged CDN for distributing media files
   */
  'enableMediaCdn'?: boolean;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'siteName',
      baseName: 'site_name',
      type: 'string',
    },
    {
      name: 'projectName',
      baseName: 'project_name',
      type: 'string',
    },
    {
      name: 'team',
      baseName: 'team',
      type: 'string',
    },
    {
      name: 'subscriptionId',
      baseName: 'subscription_id',
      type: 'string',
    },
    {
      name: 'planId',
      baseName: 'plan_id',
      type: 'InlineObject1.PlanIdEnum',
    },
    {
      name: 'siteSubdir',
      baseName: 'site_subdir',
      type: 'string',
    },
    {
      name: 'enableMediaCdn',
      baseName: 'enable_media_cdn',
      type: 'boolean',
    },
  ];

  static getAttributeTypeMap() {
    return InlineObject1.attributeTypeMap;
  }
}

export namespace InlineObject1 {
  export enum PlanIdEnum {
    Free = <any>'free',
    Tier01MonthYear = <any>'tier_01_month|year',
    Tier02MonthYear = <any>'tier_02_month|year',
    Tier03MonthYear = <any>'tier_03_month|year',
  }
}
