/**
 * Shifter API
 * Shifter API
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class InlineObject9 {
    /**
    * Flag the domain associates with Shifter CDN. [true]- Domain associates with Shifter CDN. [false]- Domain is only marked as \'attached\'. Route domain to shifter site by themselves.
    */
    'useShifterDomain'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "useShifterDomain",
            "baseName": "use_shifter_domain",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return InlineObject9.attributeTypeMap;
    }
}

