/**
 * Shifter API
 * Shifter API
 *
 * The version of the OpenAPI document: latest
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class InlineObject12 {
  /**
   * (Required) plan id
   */
  'planId'?: InlineObject12.PlanIdEnum;
  /**
   * (Not required) subscription id
   */
  'subscriptionId'?: string;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'planId',
      baseName: 'plan_id',
      type: 'InlineObject12.PlanIdEnum',
    },
    {
      name: 'subscriptionId',
      baseName: 'subscription_id',
      type: 'string',
    },
  ];

  static getAttributeTypeMap() {
    return InlineObject12.attributeTypeMap;
  }
}

export namespace InlineObject12 {
  export enum PlanIdEnum {
    _01Year = <any>'tier_01_year',
    _01Month = <any>'tier_01_month',
    _02Year = <any>'tier_02_year',
    _02Month = <any>'tier_02_month',
    _03Year = <any>'tier_03_year',
    _03Month = <any>'tier_03_month',
  }
}
