/**
 * Shifter API
 * Shifter API
 *
 * The version of the OpenAPI document: latest
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { InlineResponse200Errors } from './inlineResponse200Errors';

export class InlineResponse200 {
  'errors'?: Array<InlineResponse200Errors>;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'errors',
      baseName: 'errors',
      type: 'Array<InlineResponse200Errors>',
    },
  ];

  static getAttributeTypeMap() {
    return InlineResponse200.attributeTypeMap;
  }
}
