/**
 * Shifter API
 * Shifter API
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class InlineResponse2007 {
    'siteId'?: string;
    'hookEvent'?: string;
    'webhookUrl'?: string;
    'result'?: string;
    'jonId'?: string;
    'calledDate'?: string;
    'text'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "siteId",
            "baseName": "site_id",
            "type": "string"
        },
        {
            "name": "hookEvent",
            "baseName": "hook_event",
            "type": "string"
        },
        {
            "name": "webhookUrl",
            "baseName": "webhook_url",
            "type": "string"
        },
        {
            "name": "result",
            "baseName": "result",
            "type": "string"
        },
        {
            "name": "jonId",
            "baseName": "jon_id",
            "type": "string"
        },
        {
            "name": "calledDate",
            "baseName": "called_date",
            "type": "string"
        },
        {
            "name": "text",
            "baseName": "text",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return InlineResponse2007.attributeTypeMap;
    }
}

