/**
 * Shifter API
 * Shifter API
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { AccountLogAuthEventsEventContextData } from './accountLogAuthEventsEventContextData';
import { AccountLogAuthEventsEventFeedback } from './accountLogAuthEventsEventFeedback';
import { AccountLogAuthEventsEventRisk } from './accountLogAuthEventsEventRisk';

export class InlineResponse20012 {
    'eventId'?: string;
    'eventType'?: string;
    'creationDate'?: string;
    'eventResponse'?: string;
    'eventRisk'?: AccountLogAuthEventsEventRisk;
    'challengeResponses'?: string;
    'eventContextData'?: AccountLogAuthEventsEventContextData;
    'eventFeedback'?: AccountLogAuthEventsEventFeedback;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "eventId",
            "baseName": "EventId",
            "type": "string"
        },
        {
            "name": "eventType",
            "baseName": "EventType",
            "type": "string"
        },
        {
            "name": "creationDate",
            "baseName": "CreationDate",
            "type": "string"
        },
        {
            "name": "eventResponse",
            "baseName": "EventResponse",
            "type": "string"
        },
        {
            "name": "eventRisk",
            "baseName": "EventRisk",
            "type": "AccountLogAuthEventsEventRisk"
        },
        {
            "name": "challengeResponses",
            "baseName": "ChallengeResponses",
            "type": "string"
        },
        {
            "name": "eventContextData",
            "baseName": "EventContextData",
            "type": "AccountLogAuthEventsEventContextData"
        },
        {
            "name": "eventFeedback",
            "baseName": "EventFeedback",
            "type": "AccountLogAuthEventsEventFeedback"
        }    ];

    static getAttributeTypeMap() {
        return InlineResponse20012.attributeTypeMap;
    }
}

