/**
 * Shifter API
 * Shifter API
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class LoginPostResponse {
    /**
    * Access Token for Shifter API. This token will be expired in 1 hour.
    */
    'accessToken'?: string;
    /**
    * Refresh Token for Shifter API. This token will be expired in 7 days.
    */
    'refreshToken'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "accessToken",
            "baseName": "AccessToken",
            "type": "string"
        },
        {
            "name": "refreshToken",
            "baseName": "RefreshToken",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return LoginPostResponse.attributeTypeMap;
    }
}

