/**
 * Shifter API
 * Shifter API
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class PlanResponseMetadata {
    'sitesLimit'?: string;
    'domainSetting'?: string;
    'userLimit'?: string;
    'importArchives'?: string;
    'exportArchives'?: string;
    'backup'?: string;
    'maxTransferGb'?: string;
    'maxDiskGb'?: string;
    'enableSubuser'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "sitesLimit",
            "baseName": "sites_limit",
            "type": "string"
        },
        {
            "name": "domainSetting",
            "baseName": "domain_setting",
            "type": "string"
        },
        {
            "name": "userLimit",
            "baseName": "user_limit",
            "type": "string"
        },
        {
            "name": "importArchives",
            "baseName": "import_archives",
            "type": "string"
        },
        {
            "name": "exportArchives",
            "baseName": "export_archives",
            "type": "string"
        },
        {
            "name": "backup",
            "baseName": "backup",
            "type": "string"
        },
        {
            "name": "maxTransferGb",
            "baseName": "max_transfer_gb",
            "type": "string"
        },
        {
            "name": "maxDiskGb",
            "baseName": "max_disk_gb",
            "type": "string"
        },
        {
            "name": "enableSubuser",
            "baseName": "enable_subuser",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return PlanResponseMetadata.attributeTypeMap;
    }
}

