/**
 * Shifter API
 * Shifter API
 *
 * The version of the OpenAPI document: latest
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { StatusGetResponseMaintenance } from './statusGetResponseMaintenance';
import { StatusGetResponseUser } from './statusGetResponseUser';

export class StatusGetResponse {
  'maintenance'?: StatusGetResponseMaintenance;
  'user'?: StatusGetResponseUser;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'maintenance',
      baseName: 'maintenance',
      type: 'StatusGetResponseMaintenance',
    },
    {
      name: 'user',
      baseName: 'user',
      type: 'StatusGetResponseUser',
    },
  ];

  static getAttributeTypeMap() {
    return StatusGetResponse.attributeTypeMap;
  }
}
