/**
 * Shifter API
 * Shifter API
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { StatusGetResponseUserNotificationEmail } from './statusGetResponseUserNotificationEmail';

export class StatusGetResponseUserNotification {
    'email'?: StatusGetResponseUserNotificationEmail;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "email",
            "baseName": "email",
            "type": "StatusGetResponseUserNotificationEmail"
        }    ];

    static getAttributeTypeMap() {
        return StatusGetResponseUserNotification.attributeTypeMap;
    }
}

