/**
 * Shifter API
 * Shifter API
 *
 * The version of the OpenAPI document: latest
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class SubscriptionGetResponseInvoiceCustomerBalanceSettings {
  'consumeAppliedBalanceOnVoid'?: boolean;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'consumeAppliedBalanceOnVoid',
      baseName: 'consume_applied_balance_on_void',
      type: 'boolean',
    },
  ];

  static getAttributeTypeMap() {
    return SubscriptionGetResponseInvoiceCustomerBalanceSettings.attributeTypeMap;
  }
}
