/**
 * Shifter API
 * Shifter API
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { SubscriptionGetResponseItemsPlan } from './subscriptionGetResponseItemsPlan';
import { SubscriptionGetResponseItemsPrice } from './subscriptionGetResponseItemsPrice';

export class SubscriptionGetResponseItemsData {
    'id'?: string;
    'object'?: string;
    'billingThresholds'?: { [key: string]: object; };
    'created'?: number;
    'metadata'?: { [key: string]: object; };
    'plan'?: SubscriptionGetResponseItemsPlan;
    'price'?: SubscriptionGetResponseItemsPrice;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "object",
            "baseName": "object",
            "type": "string"
        },
        {
            "name": "billingThresholds",
            "baseName": "billing_thresholds",
            "type": "{ [key: string]: object; }"
        },
        {
            "name": "created",
            "baseName": "created",
            "type": "number"
        },
        {
            "name": "metadata",
            "baseName": "metadata",
            "type": "{ [key: string]: object; }"
        },
        {
            "name": "plan",
            "baseName": "plan",
            "type": "SubscriptionGetResponseItemsPlan"
        },
        {
            "name": "price",
            "baseName": "price",
            "type": "SubscriptionGetResponseItemsPrice"
        }    ];

    static getAttributeTypeMap() {
        return SubscriptionGetResponseItemsData.attributeTypeMap;
    }
}

