/**
 * Shifter API
 * Shifter API
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class SubscriptionGetResponseItemsPlanMetadata {
    'projectsLimit'?: string;
    'artifactLimit'?: string;
    'exportArtifact'?: boolean;
    'maxDiskGb'?: string;
    'maxTransferGb'?: string;
    'enableSubuser'?: boolean;
    'domainSetting'?: boolean;
    'emailNotification'?: boolean;
    'slackNotification'?: boolean;
    'enableWebhook'?: boolean;
    'exportAccessLog'?: boolean;
    'mediaCdn'?: boolean;
    'basicAuth'?: boolean;
    'autoBackup'?: boolean;
    'webhookWpLaunch'?: boolean;
    'exportBackup'?: boolean;
    'maxWpStartRequestDay'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "projectsLimit",
            "baseName": "projects_limit",
            "type": "string"
        },
        {
            "name": "artifactLimit",
            "baseName": "artifact_limit",
            "type": "string"
        },
        {
            "name": "exportArtifact",
            "baseName": "export_artifact",
            "type": "boolean"
        },
        {
            "name": "maxDiskGb",
            "baseName": "max_disk_gb",
            "type": "string"
        },
        {
            "name": "maxTransferGb",
            "baseName": "max_transfer_gb",
            "type": "string"
        },
        {
            "name": "enableSubuser",
            "baseName": "enable_subuser",
            "type": "boolean"
        },
        {
            "name": "domainSetting",
            "baseName": "domain_setting",
            "type": "boolean"
        },
        {
            "name": "emailNotification",
            "baseName": "email_notification",
            "type": "boolean"
        },
        {
            "name": "slackNotification",
            "baseName": "slack_notification",
            "type": "boolean"
        },
        {
            "name": "enableWebhook",
            "baseName": "enable_webhook",
            "type": "boolean"
        },
        {
            "name": "exportAccessLog",
            "baseName": "export_access_log",
            "type": "boolean"
        },
        {
            "name": "mediaCdn",
            "baseName": "media_cdn",
            "type": "boolean"
        },
        {
            "name": "basicAuth",
            "baseName": "basic_auth",
            "type": "boolean"
        },
        {
            "name": "autoBackup",
            "baseName": "auto_backup",
            "type": "boolean"
        },
        {
            "name": "webhookWpLaunch",
            "baseName": "webhook_wp_launch",
            "type": "boolean"
        },
        {
            "name": "exportBackup",
            "baseName": "export_backup",
            "type": "boolean"
        },
        {
            "name": "maxWpStartRequestDay",
            "baseName": "max_wp_start_request_day",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return SubscriptionGetResponseItemsPlanMetadata.attributeTypeMap;
    }
}

