/**
 * Shifter API
 * Shifter API
 *
 * The version of the OpenAPI document: latest
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class SubscriptionUpdateResponse {
  /**
   * Subscription ID
   */
  'id'?: string;
  /**
   * New subscription ID
   */
  'newSubscriptionId'?: string;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'id',
      baseName: 'id',
      type: 'string',
    },
    {
      name: 'newSubscriptionId',
      baseName: 'new_subscription_id',
      type: 'string',
    },
  ];

  static getAttributeTypeMap() {
    return SubscriptionUpdateResponse.attributeTypeMap;
  }
}
