/**
 * Shifter API
 * Shifter API
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class SubscriptionGetResponseBillingThresholds {
    'amountGte'?: number;
    'resetBillingCycleAnchor'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "amountGte",
            "baseName": "amount_gte",
            "type": "number"
        },
        {
            "name": "resetBillingCycleAnchor",
            "baseName": "reset_billing_cycle_anchor",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return SubscriptionGetResponseBillingThresholds.attributeTypeMap;
    }
}

