/**
 * Shifter API
 * Shifter API
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class SubscriptionGetResponseItemsPlanTiers {
    'flatAmount'?: number;
    'flatAmountDecimal'?: number;
    'unitAmount'?: number;
    'unitAmountDecimal'?: string;
    'upTo'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "flatAmount",
            "baseName": "flat_amount",
            "type": "number"
        },
        {
            "name": "flatAmountDecimal",
            "baseName": "flat_amount_decimal",
            "type": "number"
        },
        {
            "name": "unitAmount",
            "baseName": "unit_amount",
            "type": "number"
        },
        {
            "name": "unitAmountDecimal",
            "baseName": "unit_amount_decimal",
            "type": "string"
        },
        {
            "name": "upTo",
            "baseName": "up_to",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return SubscriptionGetResponseItemsPlanTiers.attributeTypeMap;
    }
}

