/**
 * Shifter API
 * Shifter API
 *
 * The version of the OpenAPI document: latest
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { SubscriptionGetResponseItemsPlanMetadata } from './subscriptionGetResponseItemsPlanMetadata';
import { SubscriptionGetResponseItemsPlanTiers } from './subscriptionGetResponseItemsPlanTiers';
import { SubscriptionGetResponseItemsPlanTransformUsage } from './subscriptionGetResponseItemsPlanTransformUsage';

export class SubscriptionGetResponseItemsPlan {
  'id'?: string;
  'object'?: string;
  'active'?: boolean;
  'aggregateUsage'?: number;
  'amount'?: number;
  'amountDecimal'?: number;
  'billingScheme'?: string;
  'created'?: number;
  'currency'?: string;
  'interval'?: string;
  'intervalCount'?: number;
  'livemode'?: boolean;
  'metadata'?: SubscriptionGetResponseItemsPlanMetadata;
  'nickname'?: string;
  'product'?: string;
  'tiers'?: Array<SubscriptionGetResponseItemsPlanTiers>;
  'tiersMode'?: string;
  'transformUsage'?: SubscriptionGetResponseItemsPlanTransformUsage;
  'trialPeriodDays'?: number;
  'usageType'?: string;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'id',
      baseName: 'id',
      type: 'string',
    },
    {
      name: 'object',
      baseName: 'object',
      type: 'string',
    },
    {
      name: 'active',
      baseName: 'active',
      type: 'boolean',
    },
    {
      name: 'aggregateUsage',
      baseName: 'aggregate_usage',
      type: 'number',
    },
    {
      name: 'amount',
      baseName: 'amount',
      type: 'number',
    },
    {
      name: 'amountDecimal',
      baseName: 'amount_decimal',
      type: 'number',
    },
    {
      name: 'billingScheme',
      baseName: 'billing_scheme',
      type: 'string',
    },
    {
      name: 'created',
      baseName: 'created',
      type: 'number',
    },
    {
      name: 'currency',
      baseName: 'currency',
      type: 'string',
    },
    {
      name: 'interval',
      baseName: 'interval',
      type: 'string',
    },
    {
      name: 'intervalCount',
      baseName: 'interval_count',
      type: 'number',
    },
    {
      name: 'livemode',
      baseName: 'livemode',
      type: 'boolean',
    },
    {
      name: 'metadata',
      baseName: 'metadata',
      type: 'SubscriptionGetResponseItemsPlanMetadata',
    },
    {
      name: 'nickname',
      baseName: 'nickname',
      type: 'string',
    },
    {
      name: 'product',
      baseName: 'product',
      type: 'string',
    },
    {
      name: 'tiers',
      baseName: 'tiers',
      type: 'Array<SubscriptionGetResponseItemsPlanTiers>',
    },
    {
      name: 'tiersMode',
      baseName: 'tiers_mode',
      type: 'string',
    },
    {
      name: 'transformUsage',
      baseName: 'transform_usage',
      type: 'SubscriptionGetResponseItemsPlanTransformUsage',
    },
    {
      name: 'trialPeriodDays',
      baseName: 'trial_period_days',
      type: 'number',
    },
    {
      name: 'usageType',
      baseName: 'usage_type',
      type: 'string',
    },
  ];

  static getAttributeTypeMap() {
    return SubscriptionGetResponseItemsPlan.attributeTypeMap;
  }
}
