/**
 * Shifter API
 * Shifter API
 *
 * The version of the OpenAPI document: latest
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class SubscriptionGetResponseItemsPlanTransformUsage {
  'divideBy'?: number;
  'round'?: string;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'divideBy',
      baseName: 'divide_by',
      type: 'number',
    },
    {
      name: 'round',
      baseName: 'round',
      type: 'string',
    },
  ];

  static getAttributeTypeMap() {
    return SubscriptionGetResponseItemsPlanTransformUsage.attributeTypeMap;
  }
}
