/**
 * Shifter API
 * Shifter API
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class TeamsResponseWithoutId {
    'teamName'?: string;
    'teamWebsite'?: string;
    'phoneNumber'?: string;
    'teamCountry'?: string;
    'teamState'?: string;
    'teamTwitter'?: string;
    'teamSize'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "teamName",
            "baseName": "team_name",
            "type": "string"
        },
        {
            "name": "teamWebsite",
            "baseName": "team_website",
            "type": "string"
        },
        {
            "name": "phoneNumber",
            "baseName": "phone_number",
            "type": "string"
        },
        {
            "name": "teamCountry",
            "baseName": "team_country",
            "type": "string"
        },
        {
            "name": "teamState",
            "baseName": "team_state",
            "type": "string"
        },
        {
            "name": "teamTwitter",
            "baseName": "team_twitter",
            "type": "string"
        },
        {
            "name": "teamSize",
            "baseName": "team_size",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return TeamsResponseWithoutId.attributeTypeMap;
    }
}

