/**
 * Shifter API
 * Shifter API
 *
 * OpenAPI spec version: latest
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class AccountLogAuthEventsEventContextData {
  'iPAddress'?: string;
  'deviceName'?: string;
  'timezone'?: string;
  'city'?: string;
  'country'?: string;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
    format: string;
  }> = [
    {
      name: 'iPAddress',
      baseName: 'IPAddress',
      type: 'string',
      format: '',
    },
    {
      name: 'deviceName',
      baseName: 'DeviceName',
      type: 'string',
      format: '',
    },
    {
      name: 'timezone',
      baseName: 'Timezone',
      type: 'string',
      format: '',
    },
    {
      name: 'city',
      baseName: 'City',
      type: 'string',
      format: '',
    },
    {
      name: 'country',
      baseName: 'Country',
      type: 'string',
      format: '',
    },
  ];

  static getAttributeTypeMap() {
    return AccountLogAuthEventsEventContextData.attributeTypeMap;
  }

  public constructor() {}
}
