/**
 * Shifter API
 * Shifter API
 *
 * OpenAPI spec version: latest
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class AccountLogAuthEventsEventRisk {
  'riskDecision'?: string;
  'riskLevel'?: string;
  'compromisedCredentialsDetected'?: boolean;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
    format: string;
  }> = [
    {
      name: 'riskDecision',
      baseName: 'RiskDecision',
      type: 'string',
      format: '',
    },
    {
      name: 'riskLevel',
      baseName: 'RiskLevel',
      type: 'string',
      format: '',
    },
    {
      name: 'compromisedCredentialsDetected',
      baseName: 'CompromisedCredentialsDetected',
      type: 'boolean',
      format: '',
    },
  ];

  static getAttributeTypeMap() {
    return AccountLogAuthEventsEventRisk.attributeTypeMap;
  }

  public constructor() {}
}
