/**
 * Shifter API
 * Shifter API
 *
 * OpenAPI spec version: latest
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class AccountLogAuthEventsEventFeedback {
  'feedbackValue'?: string;
  'provider'?: string;
  'feedbackDate'?: string;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
    format: string;
  }> = [
    {
      name: 'feedbackValue',
      baseName: 'FeedbackValue',
      type: 'string',
      format: '',
    },
    {
      name: 'provider',
      baseName: 'Provider',
      type: 'string',
      format: '',
    },
    {
      name: 'feedbackDate',
      baseName: 'FeedbackDate',
      type: 'string',
      format: '',
    },
  ];

  static getAttributeTypeMap() {
    return AccountLogAuthEventsEventFeedback.attributeTypeMap;
  }

  public constructor() {}
}
