/**
 * Shifter API
 * Shifter API
 *
 * OpenAPI spec version: latest
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class DomainGetResponse {
  /**
   * Name of domain
   */
  'domain'?: string;
  /**
   * Names of SANS(alternate names)
   */
  'subjectAlternativeNames'?: Array<string>;
  /**
   * Status of domain. [ISSUED]- Domain can attach to the shifter site. [VALIDATION_TIMED_OUT]- Domain validation was timed it out. [EXPIRED]- Domain has been expiring.
   */
  'status'?: string;
  /**
   * The time of when the domain was created
   */
  'createTime'?: string;
  /**
   * A flag which indicates the domain associates with the Shifter CDN or not. [true]- Domain associates with the Shifter CDN. [false]- Domain associates another(your own) CDN.
   */
  'isShifterCdn'?: boolean;
  /**
   * A or some reason(s) of domain validation
   */
  'failureReason'?: string;
  /**
   * Date of expire of the domain
   */
  'expiredAt'?: string;
  /**
   * Site information which domain associates with
   */
  'attachedProject'?: { [key: string]: any };

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
    format: string;
  }> = [
    {
      name: 'domain',
      baseName: 'domain',
      type: 'string',
      format: '',
    },
    {
      name: 'subjectAlternativeNames',
      baseName: 'subject_alternative_names',
      type: 'Array<string>',
      format: '',
    },
    {
      name: 'status',
      baseName: 'status',
      type: 'string',
      format: '',
    },
    {
      name: 'createTime',
      baseName: 'create_time',
      type: 'string',
      format: '',
    },
    {
      name: 'isShifterCdn',
      baseName: 'is_shifter_cdn',
      type: 'boolean',
      format: '',
    },
    {
      name: 'failureReason',
      baseName: 'failure_reason',
      type: 'string',
      format: '',
    },
    {
      name: 'expiredAt',
      baseName: 'expired_at',
      type: 'string',
      format: '',
    },
    {
      name: 'attachedProject',
      baseName: 'attached_project',
      type: '{ [key: string]: any; }',
      format: '',
    },
  ];

  static getAttributeTypeMap() {
    return DomainGetResponse.attributeTypeMap;
  }

  public constructor() {}
}
