/**
 * Shifter API
 * Shifter API
 *
 * OpenAPI spec version: latest
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { DomainValidationGetResponseCnames } from './DomainValidationGetResponseCnames';
import { HttpFile } from '../http/http';

export class DomainValidationGetResponse {
  /**
   * Name of domain
   */
  'domain'?: string;
  /**
   * Names of SANS(alternate names)
   */
  'subjectAlternativeNames'?: Array<string>;
  /**
   * Status of domain. [ISSUED]- Domain can attach to the shifter site. [VALIDATION_TIMED_OUT]- Domain validation was timed it out. [EXPIRED]- Domain has been expiring.
   */
  'status'?: string;
  /**
   * Array of validation records of domain
   */
  'cnames'?: Array<DomainValidationGetResponseCnames>;
  /**
   * The time of when the domain was created
   */
  'createTime'?: string;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
    format: string;
  }> = [
    {
      name: 'domain',
      baseName: 'domain',
      type: 'string',
      format: '',
    },
    {
      name: 'subjectAlternativeNames',
      baseName: 'subject_alternative_names',
      type: 'Array<string>',
      format: '',
    },
    {
      name: 'status',
      baseName: 'status',
      type: 'string',
      format: '',
    },
    {
      name: 'cnames',
      baseName: 'cnames',
      type: 'Array<DomainValidationGetResponseCnames>',
      format: '',
    },
    {
      name: 'createTime',
      baseName: 'create_time',
      type: 'string',
      format: '',
    },
  ];

  static getAttributeTypeMap() {
    return DomainValidationGetResponse.attributeTypeMap;
  }

  public constructor() {}
}
