/**
 * Shifter API
 * Shifter API
 *
 * OpenAPI spec version: latest
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class InlineObject12 {
  /**
   * (Required) plan id
   */
  'planId'?: InlineObject12PlanIdEnum;
  /**
   * (Not required) subscription id
   */
  'subscriptionId'?: string;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
    format: string;
  }> = [
    {
      name: 'planId',
      baseName: 'plan_id',
      type: 'InlineObject12PlanIdEnum',
      format: '',
    },
    {
      name: 'subscriptionId',
      baseName: 'subscription_id',
      type: 'string',
      format: '',
    },
  ];

  static getAttributeTypeMap() {
    return InlineObject12.attributeTypeMap;
  }

  public constructor() {}
}

export type InlineObject12PlanIdEnum =
  | 'tier_01_year'
  | 'tier_01_month'
  | 'tier_02_year'
  | 'tier_02_month'
  | 'tier_03_year'
  | 'tier_03_month';
