/**
 * Shifter API
 * Shifter API
 *
 * OpenAPI spec version: latest
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AccountLogAuthEventsEventContextData } from './AccountLogAuthEventsEventContextData';
import { AccountLogAuthEventsEventFeedback } from './AccountLogAuthEventsEventFeedback';
import { AccountLogAuthEventsEventRisk } from './AccountLogAuthEventsEventRisk';
import { HttpFile } from '../http/http';

export class InlineResponse20012 {
  'eventId'?: string;
  'eventType'?: string;
  'creationDate'?: string;
  'eventResponse'?: string;
  'eventRisk'?: AccountLogAuthEventsEventRisk;
  'challengeResponses'?: string;
  'eventContextData'?: AccountLogAuthEventsEventContextData;
  'eventFeedback'?: AccountLogAuthEventsEventFeedback;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
    format: string;
  }> = [
    {
      name: 'eventId',
      baseName: 'EventId',
      type: 'string',
      format: '',
    },
    {
      name: 'eventType',
      baseName: 'EventType',
      type: 'string',
      format: '',
    },
    {
      name: 'creationDate',
      baseName: 'CreationDate',
      type: 'string',
      format: '',
    },
    {
      name: 'eventResponse',
      baseName: 'EventResponse',
      type: 'string',
      format: '',
    },
    {
      name: 'eventRisk',
      baseName: 'EventRisk',
      type: 'AccountLogAuthEventsEventRisk',
      format: '',
    },
    {
      name: 'challengeResponses',
      baseName: 'ChallengeResponses',
      type: 'string',
      format: '',
    },
    {
      name: 'eventContextData',
      baseName: 'EventContextData',
      type: 'AccountLogAuthEventsEventContextData',
      format: '',
    },
    {
      name: 'eventFeedback',
      baseName: 'EventFeedback',
      type: 'AccountLogAuthEventsEventFeedback',
      format: '',
    },
  ];

  static getAttributeTypeMap() {
    return InlineResponse20012.attributeTypeMap;
  }

  public constructor() {}
}
