/**
 * Shifter API
 * Shifter API
 *
 * OpenAPI spec version: latest
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { TeamsResponseWithId } from './TeamsResponseWithId';
import { HttpFile } from '../http/http';

export class InlineResponse2002 {
  'owner'?: Array<TeamsResponseWithId>;
  'member'?: Array<TeamsResponseWithId>;
  /**
   * If user belongs to only one team, Warning message
   */
  'message'?: string;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
    format: string;
  }> = [
    {
      name: 'owner',
      baseName: 'owner',
      type: 'Array<TeamsResponseWithId>',
      format: '',
    },
    {
      name: 'member',
      baseName: 'member',
      type: 'Array<TeamsResponseWithId>',
      format: '',
    },
    {
      name: 'message',
      baseName: 'message',
      type: 'string',
      format: '',
    },
  ];

  static getAttributeTypeMap() {
    return InlineResponse2002.attributeTypeMap;
  }

  public constructor() {}
}
