/**
 * Shifter API
 * Shifter API
 *
 * OpenAPI spec version: latest
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class InlineResponse200Errors {
  'timestamp'?: string;
  'errorLevel'?: string;
  'message'?: string;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
    format: string;
  }> = [
    {
      name: 'timestamp',
      baseName: 'timestamp',
      type: 'string',
      format: '',
    },
    {
      name: 'errorLevel',
      baseName: 'error_level',
      type: 'string',
      format: '',
    },
    {
      name: 'message',
      baseName: 'message',
      type: 'string',
      format: '',
    },
  ];

  static getAttributeTypeMap() {
    return InlineResponse200Errors.attributeTypeMap;
  }

  public constructor() {}
}
