/**
 * Shifter API
 * Shifter API
 *
 * OpenAPI spec version: latest
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class InlineObject9 {
  /**
   * Flag the domain associates with Shifter CDN. [true]- Domain associates with Shifter CDN. [false]- Domain is only marked as 'attached'. Route domain to shifter site by themselves.
   */
  'useShifterDomain'?: boolean;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
    format: string;
  }> = [
    {
      name: 'useShifterDomain',
      baseName: 'use_shifter_domain',
      type: 'boolean',
      format: '',
    },
  ];

  static getAttributeTypeMap() {
    return InlineObject9.attributeTypeMap;
  }

  public constructor() {}
}
