/**
 * Shifter API
 * Shifter API
 *
 * OpenAPI spec version: latest
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class InlineResponse20013 {
  'domain'?: string;
  'subjectAlternativeNames'?: Array<string>;
  'status'?: string;
  'createTime'?: string;
  'validationEmails'?: Array<string>;
  'isShifterCdn'?: boolean;
  'failureReason'?: string;
  'expiredAt'?: string;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
    format: string;
  }> = [
    {
      name: 'domain',
      baseName: 'domain',
      type: 'string',
      format: '',
    },
    {
      name: 'subjectAlternativeNames',
      baseName: 'subject_alternative_names',
      type: 'Array<string>',
      format: '',
    },
    {
      name: 'status',
      baseName: 'status',
      type: 'string',
      format: '',
    },
    {
      name: 'createTime',
      baseName: 'create_time',
      type: 'string',
      format: '',
    },
    {
      name: 'validationEmails',
      baseName: 'validation_emails',
      type: 'Array<string>',
      format: '',
    },
    {
      name: 'isShifterCdn',
      baseName: 'is_shifter_cdn',
      type: 'boolean',
      format: '',
    },
    {
      name: 'failureReason',
      baseName: 'failure_reason',
      type: 'string',
      format: '',
    },
    {
      name: 'expiredAt',
      baseName: 'expired_at',
      type: 'string',
      format: '',
    },
  ];

  static getAttributeTypeMap() {
    return InlineResponse20013.attributeTypeMap;
  }

  public constructor() {}
}
