/**
 * Shifter API
 * Shifter API
 *
 * OpenAPI spec version: latest
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { InlineResponse200Errors } from './InlineResponse200Errors';
import { HttpFile } from '../http/http';

export class InlineResponse200 {
  'errors'?: Array<InlineResponse200Errors>;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
    format: string;
  }> = [
    {
      name: 'errors',
      baseName: 'errors',
      type: 'Array<InlineResponse200Errors>',
      format: '',
    },
  ];

  static getAttributeTypeMap() {
    return InlineResponse200.attributeTypeMap;
  }

  public constructor() {}
}
