/**
 * Shifter API
 * Shifter API
 *
 * OpenAPI spec version: latest
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class InlineObject7 {
  /**
   * filter by status. [valid_only]- list only domains that validation succeeded. [valid_and_expired]- list domains that status is valid or expired.
   */
  'filter'?: string;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
    format: string;
  }> = [
    {
      name: 'filter',
      baseName: 'filter',
      type: 'string',
      format: '',
    },
  ];

  static getAttributeTypeMap() {
    return InlineObject7.attributeTypeMap;
  }

  public constructor() {}
}
