/**
 * Shifter API
 * Shifter API
 *
 * OpenAPI spec version: latest
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class InlineObject14 {
  'cardExpMonth'?: string;
  'cardExpYear'?: string;
  'cardLast4'?: string;
  'cardId'?: string;
  'cardToken'?: string;
  'cardBrand'?: string;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
    format: string;
  }> = [
    {
      name: 'cardExpMonth',
      baseName: 'card_exp_month',
      type: 'string',
      format: '',
    },
    {
      name: 'cardExpYear',
      baseName: 'card_exp_year',
      type: 'string',
      format: '',
    },
    {
      name: 'cardLast4',
      baseName: 'card_last4',
      type: 'string',
      format: '',
    },
    {
      name: 'cardId',
      baseName: 'card_id',
      type: 'string',
      format: '',
    },
    {
      name: 'cardToken',
      baseName: 'card_token',
      type: 'string',
      format: '',
    },
    {
      name: 'cardBrand',
      baseName: 'card_brand',
      type: 'string',
      format: '',
    },
  ];

  static getAttributeTypeMap() {
    return InlineObject14.attributeTypeMap;
  }

  public constructor() {}
}
