/**
 * Shifter API
 * Shifter API
 *
 * OpenAPI spec version: latest
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class InlineObject25 {
  'eventType'?: string;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
    format: string;
  }> = [
    {
      name: 'eventType',
      baseName: 'event_type',
      type: 'string',
      format: '',
    },
  ];

  static getAttributeTypeMap() {
    return InlineObject25.attributeTypeMap;
  }

  public constructor() {}
}
