/**
 * Shifter API
 * Shifter API
 *
 * OpenAPI spec version: latest
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class InlineResponse201 {
  'notificationId'?: string;
  /**
   * The password of emergency user. This password is only returned during emergency requests.
   */
  'emergencyPassword'?: string;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
    format: string;
  }> = [
    {
      name: 'notificationId',
      baseName: 'notification_id',
      type: 'string',
      format: '',
    },
    {
      name: 'emergencyPassword',
      baseName: 'emergency_password',
      type: 'string',
      format: '',
    },
  ];

  static getAttributeTypeMap() {
    return InlineResponse201.attributeTypeMap;
  }

  public constructor() {}
}
