/**
 * Shifter API
 * Shifter API
 *
 * OpenAPI spec version: latest
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class InlineObject6 {
  /**
   * s3 bucket name to transfer access log
   */
  'bucketName'?: string;
  /**
   * domain which bucket is placed on
   */
  'domain'?: string;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
    format: string;
  }> = [
    {
      name: 'bucketName',
      baseName: 'bucket_name',
      type: 'string',
      format: '',
    },
    {
      name: 'domain',
      baseName: 'domain',
      type: 'string',
      format: '',
    },
  ];

  static getAttributeTypeMap() {
    return InlineObject6.attributeTypeMap;
  }

  public constructor() {}
}
