/**
 * Shifter API
 * Shifter API
 *
 * OpenAPI spec version: latest
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class LoginPostResponse {
  /**
   * Access Token for Shifter API. This token will be expired in 1 hour.
   */
  'accessToken'?: string;
  /**
   * Refresh Token for Shifter API. This token will be expired in 7 days.
   */
  'refreshToken'?: string;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
    format: string;
  }> = [
    {
      name: 'accessToken',
      baseName: 'AccessToken',
      type: 'string',
      format: '',
    },
    {
      name: 'refreshToken',
      baseName: 'RefreshToken',
      type: 'string',
      format: '',
    },
  ];

  static getAttributeTypeMap() {
    return LoginPostResponse.attributeTypeMap;
  }

  public constructor() {}
}
