/**
 * Shifter API
 * Shifter API
 *
 * OpenAPI spec version: latest
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class PlanResponseMetadata {
  'sitesLimit'?: string;
  'domainSetting'?: string;
  'userLimit'?: string;
  'importArchives'?: string;
  'exportArchives'?: string;
  'backup'?: string;
  'maxTransferGb'?: string;
  'maxDiskGb'?: string;
  'enableSubuser'?: string;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
    format: string;
  }> = [
    {
      name: 'sitesLimit',
      baseName: 'sites_limit',
      type: 'string',
      format: '',
    },
    {
      name: 'domainSetting',
      baseName: 'domain_setting',
      type: 'string',
      format: '',
    },
    {
      name: 'userLimit',
      baseName: 'user_limit',
      type: 'string',
      format: '',
    },
    {
      name: 'importArchives',
      baseName: 'import_archives',
      type: 'string',
      format: '',
    },
    {
      name: 'exportArchives',
      baseName: 'export_archives',
      type: 'string',
      format: '',
    },
    {
      name: 'backup',
      baseName: 'backup',
      type: 'string',
      format: '',
    },
    {
      name: 'maxTransferGb',
      baseName: 'max_transfer_gb',
      type: 'string',
      format: '',
    },
    {
      name: 'maxDiskGb',
      baseName: 'max_disk_gb',
      type: 'string',
      format: '',
    },
    {
      name: 'enableSubuser',
      baseName: 'enable_subuser',
      type: 'string',
      format: '',
    },
  ];

  static getAttributeTypeMap() {
    return PlanResponseMetadata.attributeTypeMap;
  }

  public constructor() {}
}
