/**
 * Shifter API
 * Shifter API
 *
 * OpenAPI spec version: latest
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PlanResponseMetadata } from './PlanResponseMetadata';
import { HttpFile } from '../http/http';

export class PlanResponse {
  'id'?: string;
  'object'?: string;
  'amount'?: number;
  'created'?: string;
  'currency'?: string;
  'interval'?: string;
  'intervalCount'?: number;
  'livemode'?: boolean;
  'name'?: string;
  'trialPeriodDays'?: number;
  'metadata'?: PlanResponseMetadata;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
    format: string;
  }> = [
    {
      name: 'id',
      baseName: 'id',
      type: 'string',
      format: '',
    },
    {
      name: 'object',
      baseName: 'object',
      type: 'string',
      format: '',
    },
    {
      name: 'amount',
      baseName: 'amount',
      type: 'number',
      format: '',
    },
    {
      name: 'created',
      baseName: 'created',
      type: 'string',
      format: '',
    },
    {
      name: 'currency',
      baseName: 'currency',
      type: 'string',
      format: '',
    },
    {
      name: 'interval',
      baseName: 'interval',
      type: 'string',
      format: '',
    },
    {
      name: 'intervalCount',
      baseName: 'interval_count',
      type: 'number',
      format: '',
    },
    {
      name: 'livemode',
      baseName: 'livemode',
      type: 'boolean',
      format: '',
    },
    {
      name: 'name',
      baseName: 'name',
      type: 'string',
      format: '',
    },
    {
      name: 'trialPeriodDays',
      baseName: 'trial_period_days',
      type: 'number',
      format: '',
    },
    {
      name: 'metadata',
      baseName: 'metadata',
      type: 'PlanResponseMetadata',
      format: '',
    },
  ];

  static getAttributeTypeMap() {
    return PlanResponse.attributeTypeMap;
  }

  public constructor() {}
}
