/**
 * Shifter API
 * Shifter API
 *
 * OpenAPI spec version: latest
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class RoleGetResponse {
  /**
   * Name of the role
   */
  'name'?: string;
  /**
   * if this value is true, the role has been deprecated.
   */
  'deprecated'?: boolean;
  /**
   * description of the role
   */
  'description'?: string;
  /**
   * Access policies that associated with the role
   */
  'policies'?: Array<string>;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
    format: string;
  }> = [
    {
      name: 'name',
      baseName: 'name',
      type: 'string',
      format: '',
    },
    {
      name: 'deprecated',
      baseName: 'deprecated',
      type: 'boolean',
      format: '',
    },
    {
      name: 'description',
      baseName: 'description',
      type: 'string',
      format: '',
    },
    {
      name: 'policies',
      baseName: 'policies',
      type: 'Array<string>',
      format: '',
    },
  ];

  static getAttributeTypeMap() {
    return RoleGetResponse.attributeTypeMap;
  }

  public constructor() {}
}
