/**
 * Shifter API
 * Shifter API
 *
 * OpenAPI spec version: latest
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class SiteCreateResponse {
  /**
   * ID of the site
   */
  'projectId'?: string;
  /**
   * Name of the site
   */
  'projectName'?: string;
  /**
   * CDN url of the Site
   */
  'shifterCdnUrl'?: string;
  /**
   * Subscription ID which was associated to the site
   */
  'subscriptionId'?: string;
  /**
   * Plan ID which was associated to the site
   */
  'planId'?: string;
  /**
   * Team ID which was associated to the site
   */
  'teamId'?: string;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
    format: string;
  }> = [
    {
      name: 'projectId',
      baseName: 'project_id',
      type: 'string',
      format: '',
    },
    {
      name: 'projectName',
      baseName: 'project_name',
      type: 'string',
      format: '',
    },
    {
      name: 'shifterCdnUrl',
      baseName: 'shifter_cdn_url',
      type: 'string',
      format: '',
    },
    {
      name: 'subscriptionId',
      baseName: 'subscription_id',
      type: 'string',
      format: '',
    },
    {
      name: 'planId',
      baseName: 'plan_id',
      type: 'string',
      format: '',
    },
    {
      name: 'teamId',
      baseName: 'team_id',
      type: 'string',
      format: '',
    },
  ];

  static getAttributeTypeMap() {
    return SiteCreateResponse.attributeTypeMap;
  }

  public constructor() {}
}
