/**
 * Shifter API
 * Shifter API
 *
 * OpenAPI spec version: latest
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class SiteResponse {
  /**
   * ID of the site
   */
  'projectId'?: string;
  'siteId'?: string;
  /**
   * Name of the site
   */
  'projectName'?: string;
  'siteName'?: string;
  /**
   * Status of the site. [inuse] - This status indicates WordPress is not running, [inservice] - This status indicates WordPress is running(User or team member are currently editing something)
   */
  'stockState'?: string;
  /**
   * Owner of the site
   */
  'projectOwner'?: string;
  'siteOwner'?: string;
  /**
   * The url of WordPress which is currently running. This value is set empty when WordPress is not running.
   */
  'wordpressSiteUrl'?: string;
  /**
   * Custom domain which was associated to the site. This value is set empty when no custom domain was associated.
   */
  'domain'?: string;
  /**
   * PHP version which WordPress uses. This parameter is set the latest version by the system.
   */
  'phpVersion'?: string;
  /**
   * Public URL of the site. This URL is provides the system. User can not change.
   */
  'accessUrl'?: string;
  /**
   * The time which site has been updated
   */
  'updateTime'?: string;
  'lastLaunched'?: string;
  /**
   * Public URL of the site. This URL is provides the system. User can not change.
   */
  'diskUsage'?: number;
  /**
   * The way of publish. Only \"shifter_cdn\"
   */
  'deployType'?: string;
  /**
   * Original AWS CloudFront URL.
   */
  'rawUrl'?: string;
  /**
   * Date which the site created
   */
  'createTime'?: string;
  /**
   * Whether automatic deployment is enable or not
   */
  'automation'?: boolean;
  /**
   * Status of generating process. [ingenerate]- publishing (Generate static site) is currently running. [inuse]- Publishing is currently not running.
   */
  'generateState'?: string;
  /**
   * Unix Epoch(seconds) which indicates trial will be expired. This property only provides when the site is in trial.
   */
  'trial'?: number;
  /**
   * Subscription ID which the site associates with
   */
  'subscriptionId'?: string;
  /**
   * Plan ID which the site associates with
   */
  'planId'?: string;
  /**
   * (deprecated) Team ID which the site belongs to
   */
  'orgId'?: string;
  /**
   * Team ID which the site belongs to
   */
  'teamId'?: string;
  /**
   * Whether All in one WP migration feature is currently enable or not
   */
  'enableAi1wmBackup'?: boolean;
  /**
   * Whether media_cdn feature is currently enable or not
   */
  'enableMediaCdn'?: boolean;
  /**
   * The key of media cdn of the site
   */
  'mediaCdnKey'?: string;
  /**
   * Whether basic authentication feature is currently enable or not
   */
  'basicAuth'?: boolean;
  /**
   * Alternate domain which the site will be publish as this domain.
   */
  'selectedDomain'?: string;
  /**
   * Root directory in the WordPress.
   */
  'subdirName'?: string;
  /**
   * URL which Access Log of Shifter CDN will be stored.
   */
  'accessLogPath'?: string;
  /**
   * Whether site delete protection feature is currently enable or not
   */
  'deleteProtection'?: boolean;
  /**
   * Date which previous PHP error in WordPress occurred.
   */
  'lastErrorOccurrenceDate'?: string;
  /**
   * Whether Pay As You Go of Data transfer feature is currently enable or not
   */
  'enableCdnAutocharge'?: boolean;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
    format: string;
  }> = [
    {
      name: 'projectId',
      baseName: 'project_id',
      type: 'string',
      format: '',
    },
    {
      name: 'siteId',
      baseName: 'site_id',
      type: 'string',
      format: '',
    },
    {
      name: 'projectName',
      baseName: 'project_name',
      type: 'string',
      format: '',
    },
    {
      name: 'siteName',
      baseName: 'site_name',
      type: 'string',
      format: '',
    },
    {
      name: 'stockState',
      baseName: 'stock_state',
      type: 'string',
      format: '',
    },
    {
      name: 'projectOwner',
      baseName: 'project_owner',
      type: 'string',
      format: '',
    },
    {
      name: 'siteOwner',
      baseName: 'site_owner',
      type: 'string',
      format: '',
    },
    {
      name: 'wordpressSiteUrl',
      baseName: 'wordpress_site_url',
      type: 'string',
      format: '',
    },
    {
      name: 'domain',
      baseName: 'domain',
      type: 'string',
      format: '',
    },
    {
      name: 'phpVersion',
      baseName: 'php_version',
      type: 'string',
      format: '',
    },
    {
      name: 'accessUrl',
      baseName: 'access_url',
      type: 'string',
      format: '',
    },
    {
      name: 'updateTime',
      baseName: 'update_time',
      type: 'string',
      format: '',
    },
    {
      name: 'lastLaunched',
      baseName: 'last_launched',
      type: 'string',
      format: '',
    },
    {
      name: 'diskUsage',
      baseName: 'disk_usage',
      type: 'number',
      format: '',
    },
    {
      name: 'deployType',
      baseName: 'deploy_type',
      type: 'string',
      format: '',
    },
    {
      name: 'rawUrl',
      baseName: 'raw_url',
      type: 'string',
      format: '',
    },
    {
      name: 'createTime',
      baseName: 'create_time',
      type: 'string',
      format: '',
    },
    {
      name: 'automation',
      baseName: 'automation',
      type: 'boolean',
      format: '',
    },
    {
      name: 'generateState',
      baseName: 'generate_state',
      type: 'string',
      format: '',
    },
    {
      name: 'trial',
      baseName: 'trial',
      type: 'number',
      format: '',
    },
    {
      name: 'subscriptionId',
      baseName: 'subscription_id',
      type: 'string',
      format: '',
    },
    {
      name: 'planId',
      baseName: 'plan_id',
      type: 'string',
      format: '',
    },
    {
      name: 'orgId',
      baseName: 'org_id',
      type: 'string',
      format: '',
    },
    {
      name: 'teamId',
      baseName: 'team_id',
      type: 'string',
      format: '',
    },
    {
      name: 'enableAi1wmBackup',
      baseName: 'enable_ai1wm_backup',
      type: 'boolean',
      format: '',
    },
    {
      name: 'enableMediaCdn',
      baseName: 'enable_media_cdn',
      type: 'boolean',
      format: '',
    },
    {
      name: 'mediaCdnKey',
      baseName: 'media_cdn_key',
      type: 'string',
      format: '',
    },
    {
      name: 'basicAuth',
      baseName: 'basic_auth',
      type: 'boolean',
      format: '',
    },
    {
      name: 'selectedDomain',
      baseName: 'selected_domain',
      type: 'string',
      format: '',
    },
    {
      name: 'subdirName',
      baseName: 'subdir_name',
      type: 'string',
      format: '',
    },
    {
      name: 'accessLogPath',
      baseName: 'access_log_path',
      type: 'string',
      format: '',
    },
    {
      name: 'deleteProtection',
      baseName: 'delete_protection',
      type: 'boolean',
      format: '',
    },
    {
      name: 'lastErrorOccurrenceDate',
      baseName: 'last_error_occurrence_date',
      type: 'string',
      format: '',
    },
    {
      name: 'enableCdnAutocharge',
      baseName: 'enable_cdn_autocharge',
      type: 'boolean',
      format: '',
    },
  ];

  static getAttributeTypeMap() {
    return SiteResponse.attributeTypeMap;
  }

  public constructor() {}
}
