/**
 * Shifter API
 * Shifter API
 *
 * OpenAPI spec version: latest
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class StatusGetResponseMaintenance {
  /**
   * Description of status of current Shifter system
   */
  'message'?: string;
  /**
   * Target components of maintenance.
   */
  'target'?: Array<string>;
  /**
   * Current system status. [not_maintenance]- Shifter is not in maintenance. [now_maintenance]- Shifter is currently in maintenance. [pre_maintenance]- Shifter will be into maintenance soon.
   */
  'status'?: string;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
    format: string;
  }> = [
    {
      name: 'message',
      baseName: 'message',
      type: 'string',
      format: '',
    },
    {
      name: 'target',
      baseName: 'target',
      type: 'Array<string>',
      format: '',
    },
    {
      name: 'status',
      baseName: 'status',
      type: 'string',
      format: '',
    },
  ];

  static getAttributeTypeMap() {
    return StatusGetResponseMaintenance.attributeTypeMap;
  }

  public constructor() {}
}
