/**
 * Shifter API
 * Shifter API
 *
 * OpenAPI spec version: latest
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
 * (deprecated)
 */
export class StatusGetResponseUserGroup {
  /**
   * Name of the group.
   */
  'name'?: string;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
    format: string;
  }> = [
    {
      name: 'name',
      baseName: 'name',
      type: 'string',
      format: '',
    },
  ];

  static getAttributeTypeMap() {
    return StatusGetResponseUserGroup.attributeTypeMap;
  }

  public constructor() {}
}
