/**
 * Shifter API
 * Shifter API
 *
 * OpenAPI spec version: latest
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { StatusGetResponseMaintenance } from './StatusGetResponseMaintenance';
import { StatusGetResponseUser } from './StatusGetResponseUser';
import { HttpFile } from '../http/http';

export class StatusGetResponse {
  'maintenance'?: StatusGetResponseMaintenance;
  'user'?: StatusGetResponseUser;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
    format: string;
  }> = [
    {
      name: 'maintenance',
      baseName: 'maintenance',
      type: 'StatusGetResponseMaintenance',
      format: '',
    },
    {
      name: 'user',
      baseName: 'user',
      type: 'StatusGetResponseUser',
      format: '',
    },
  ];

  static getAttributeTypeMap() {
    return StatusGetResponse.attributeTypeMap;
  }

  public constructor() {}
}
