/**
 * Shifter API
 * Shifter API
 *
 * OpenAPI spec version: latest
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { StatusGetResponseUserNotificationEmail } from './StatusGetResponseUserNotificationEmail';
import { HttpFile } from '../http/http';

export class StatusGetResponseUserNotification {
  'email'?: StatusGetResponseUserNotificationEmail;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
    format: string;
  }> = [
    {
      name: 'email',
      baseName: 'email',
      type: 'StatusGetResponseUserNotificationEmail',
      format: '',
    },
  ];

  static getAttributeTypeMap() {
    return StatusGetResponseUserNotification.attributeTypeMap;
  }

  public constructor() {}
}
