/**
 * Shifter API
 * Shifter API
 *
 * OpenAPI spec version: latest
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class SubscriptionGetResponseBillingThresholds {
  'amountGte'?: number;
  'resetBillingCycleAnchor'?: boolean;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
    format: string;
  }> = [
    {
      name: 'amountGte',
      baseName: 'amount_gte',
      type: 'number',
      format: '',
    },
    {
      name: 'resetBillingCycleAnchor',
      baseName: 'reset_billing_cycle_anchor',
      type: 'boolean',
      format: '',
    },
  ];

  static getAttributeTypeMap() {
    return SubscriptionGetResponseBillingThresholds.attributeTypeMap;
  }

  public constructor() {}
}
