/**
 * Shifter API
 * Shifter API
 *
 * OpenAPI spec version: latest
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class SubscriptionGetResponsePendingUpdate {
  'billingCycleAnchor'?: number;
  'expiresAt'?: number;
  'subscriptionItems'?: Array<{ [key: string]: any }>;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
    format: string;
  }> = [
    {
      name: 'billingCycleAnchor',
      baseName: 'billing_cycle_anchor',
      type: 'number',
      format: '',
    },
    {
      name: 'expiresAt',
      baseName: 'expires_at',
      type: 'number',
      format: '',
    },
    {
      name: 'subscriptionItems',
      baseName: 'subscription_items',
      type: 'Array<{ [key: string]: any; }>',
      format: '',
    },
  ];

  static getAttributeTypeMap() {
    return SubscriptionGetResponsePendingUpdate.attributeTypeMap;
  }

  public constructor() {}
}
