/**
 * Shifter API
 * Shifter API
 *
 * OpenAPI spec version: latest
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SubscriptionGetResponseItemsData } from './SubscriptionGetResponseItemsData';
import { HttpFile } from '../http/http';

export class SubscriptionGetResponseItems {
  'object'?: string;
  'data'?: Array<SubscriptionGetResponseItemsData>;
  'hasMore'?: boolean;
  'totalCount'?: number;
  'url'?: string;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
    format: string;
  }> = [
    {
      name: 'object',
      baseName: 'object',
      type: 'string',
      format: '',
    },
    {
      name: 'data',
      baseName: 'data',
      type: 'Array<SubscriptionGetResponseItemsData>',
      format: '',
    },
    {
      name: 'hasMore',
      baseName: 'has_more',
      type: 'boolean',
      format: '',
    },
    {
      name: 'totalCount',
      baseName: 'total_count',
      type: 'number',
      format: '',
    },
    {
      name: 'url',
      baseName: 'url',
      type: 'string',
      format: '',
    },
  ];

  static getAttributeTypeMap() {
    return SubscriptionGetResponseItems.attributeTypeMap;
  }

  public constructor() {}
}
