/**
 * Shifter API
 * Shifter API
 *
 * OpenAPI spec version: latest
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class SubscriptionUpdateResponse {
  /**
   * Subscription ID
   */
  'id'?: string;
  /**
   * New subscription ID
   */
  'newSubscriptionId'?: string;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
    format: string;
  }> = [
    {
      name: 'id',
      baseName: 'id',
      type: 'string',
      format: '',
    },
    {
      name: 'newSubscriptionId',
      baseName: 'new_subscription_id',
      type: 'string',
      format: '',
    },
  ];

  static getAttributeTypeMap() {
    return SubscriptionUpdateResponse.attributeTypeMap;
  }

  public constructor() {}
}
