/**
 * Shifter API
 * Shifter API
 *
 * OpenAPI spec version: latest
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class SubscriptionGetResponseItemsPriceRecurring {
  'aggregateUsage'?: string;
  'interval'?: number;
  'intervalCount'?: number;
  'trialPeriodDays'?: number;
  'usageType'?: string;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
    format: string;
  }> = [
    {
      name: 'aggregateUsage',
      baseName: 'aggregate_usage',
      type: 'string',
      format: '',
    },
    {
      name: 'interval',
      baseName: 'interval',
      type: 'number',
      format: '',
    },
    {
      name: 'intervalCount',
      baseName: 'interval_count',
      type: 'number',
      format: '',
    },
    {
      name: 'trialPeriodDays',
      baseName: 'trial_period_days',
      type: 'number',
      format: '',
    },
    {
      name: 'usageType',
      baseName: 'usage_type',
      type: 'string',
      format: '',
    },
  ];

  static getAttributeTypeMap() {
    return SubscriptionGetResponseItemsPriceRecurring.attributeTypeMap;
  }

  public constructor() {}
}
