/**
 * Shifter API
 * Shifter API
 *
 * OpenAPI spec version: latest
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class SubscriptionGetResponseDefaultTaxRates {
  'id'?: string;
  'object'?: string;
  'active'?: boolean;
  'country'?: string;
  'created'?: number;
  'description'?: string;
  'displayName'?: string;
  'inclusive'?: boolean;
  'jurisdiction'?: string;
  'livemode'?: boolean;
  'metadata'?: { [key: string]: any };
  'percentage'?: number;
  'state'?: string;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
    format: string;
  }> = [
    {
      name: 'id',
      baseName: 'id',
      type: 'string',
      format: '',
    },
    {
      name: 'object',
      baseName: 'object',
      type: 'string',
      format: '',
    },
    {
      name: 'active',
      baseName: 'active',
      type: 'boolean',
      format: '',
    },
    {
      name: 'country',
      baseName: 'country',
      type: 'string',
      format: '',
    },
    {
      name: 'created',
      baseName: 'created',
      type: 'number',
      format: '',
    },
    {
      name: 'description',
      baseName: 'description',
      type: 'string',
      format: '',
    },
    {
      name: 'displayName',
      baseName: 'display_name',
      type: 'string',
      format: '',
    },
    {
      name: 'inclusive',
      baseName: 'inclusive',
      type: 'boolean',
      format: '',
    },
    {
      name: 'jurisdiction',
      baseName: 'jurisdiction',
      type: 'string',
      format: '',
    },
    {
      name: 'livemode',
      baseName: 'livemode',
      type: 'boolean',
      format: '',
    },
    {
      name: 'metadata',
      baseName: 'metadata',
      type: '{ [key: string]: any; }',
      format: '',
    },
    {
      name: 'percentage',
      baseName: 'percentage',
      type: 'number',
      format: '',
    },
    {
      name: 'state',
      baseName: 'state',
      type: 'string',
      format: '',
    },
  ];

  static getAttributeTypeMap() {
    return SubscriptionGetResponseDefaultTaxRates.attributeTypeMap;
  }

  public constructor() {}
}
