/**
 * Shifter API
 * Shifter API
 *
 * OpenAPI spec version: latest
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class TeamsResponseWithId {
  'teamId'?: string;
  'teamName'?: string;
  'teamWebsite'?: string;
  'phoneNumber'?: string;
  'teamCountry'?: string;
  'teamState'?: string;
  'teamTwitter'?: string;
  'teamSize'?: string;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
    format: string;
  }> = [
    {
      name: 'teamId',
      baseName: 'team_id',
      type: 'string',
      format: '',
    },
    {
      name: 'teamName',
      baseName: 'team_name',
      type: 'string',
      format: '',
    },
    {
      name: 'teamWebsite',
      baseName: 'team_website',
      type: 'string',
      format: '',
    },
    {
      name: 'phoneNumber',
      baseName: 'phone_number',
      type: 'string',
      format: '',
    },
    {
      name: 'teamCountry',
      baseName: 'team_country',
      type: 'string',
      format: '',
    },
    {
      name: 'teamState',
      baseName: 'team_state',
      type: 'string',
      format: '',
    },
    {
      name: 'teamTwitter',
      baseName: 'team_twitter',
      type: 'string',
      format: '',
    },
    {
      name: 'teamSize',
      baseName: 'team_size',
      type: 'string',
      format: '',
    },
  ];

  static getAttributeTypeMap() {
    return TeamsResponseWithId.attributeTypeMap;
  }

  public constructor() {}
}
