/**
 * Shifter API
 * Shifter API
 *
 * OpenAPI spec version: latest
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class UsageSummaryGetResponse {
  /**
   * Time that previous update of statistics
   */
  'updateTime'?: string;
  /**
   * Number of sites
   */
  'sitesCount'?: number;
  /**
   * Total giga bytes of storage usage.
   */
  'diskTotal'?: number;
  /**
   * Total transfer giga bytes
   */
  'transferTotal'?: number;
  /**
   * Shifter account name
   */
  'userName'?: string;
  /**
   * Target month of statistics
   */
  'trackMonth'?: number;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
    format: string;
  }> = [
    {
      name: 'updateTime',
      baseName: 'update_time',
      type: 'string',
      format: '',
    },
    {
      name: 'sitesCount',
      baseName: 'sites_count',
      type: 'number',
      format: '',
    },
    {
      name: 'diskTotal',
      baseName: 'disk_total',
      type: 'number',
      format: '',
    },
    {
      name: 'transferTotal',
      baseName: 'transfer_total',
      type: 'number',
      format: '',
    },
    {
      name: 'userName',
      baseName: 'user_name',
      type: 'string',
      format: '',
    },
    {
      name: 'trackMonth',
      baseName: 'track_month',
      type: 'number',
      format: '',
    },
  ];

  static getAttributeTypeMap() {
    return UsageSummaryGetResponse.attributeTypeMap;
  }

  public constructor() {}
}
